/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetointegrador;

import javax.swing.JOptionPane;

/**
 *
 * @author felip_000
 */
public class FrameQuiz1 extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameQuiz1
     */
    public FrameQuiz1() {
        super("Questão 1");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perguntaLabel1 = new javax.swing.JLabel();
        respostaq1RadioButton1 = new javax.swing.JRadioButton();
        respostaq1RadioButton2 = new javax.swing.JRadioButton();
        respostaq1RadioButton3 = new javax.swing.JRadioButton();
        respostaq1RadioButton4 = new javax.swing.JRadioButton();
        proximoButton = new javax.swing.JButton();
        retornaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Questão 1"));

        perguntaLabel1.setText("Pergunta 1");
        perguntaLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perguntaLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        respostaq1RadioButton1.setText("Resposta1q1");
        respostaq1RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaq1RadioButton1ActionPerformed(evt);
            }
        });

        respostaq1RadioButton2.setText("Resposta2q1");
        respostaq1RadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaq1RadioButton2ActionPerformed(evt);
            }
        });

        respostaq1RadioButton3.setText("Resposta3q1");
        respostaq1RadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaq1RadioButton3ActionPerformed(evt);
            }
        });

        respostaq1RadioButton4.setText("Resposta4q1");
        respostaq1RadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaq1RadioButton4ActionPerformed(evt);
            }
        });

        proximoButton.setText("Próxima");
        proximoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoButtonActionPerformed(evt);
            }
        });

        retornaButton.setText("Retornar");
        retornaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perguntaLabel1)
                            .addComponent(respostaq1RadioButton1)
                            .addComponent(respostaq1RadioButton2)
                            .addComponent(respostaq1RadioButton3)
                            .addComponent(respostaq1RadioButton4))
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(retornaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proximoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(perguntaLabel1)
                .addGap(18, 18, 18)
                .addComponent(respostaq1RadioButton1)
                .addGap(18, 18, 18)
                .addComponent(respostaq1RadioButton2)
                .addGap(18, 18, 18)
                .addComponent(respostaq1RadioButton3)
                .addGap(18, 18, 18)
                .addComponent(respostaq1RadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void respostaq1RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaq1RadioButton1ActionPerformed
        if (respostaq1RadioButton1.isSelected()){
            respostaq1RadioButton2.setSelected(false);
            respostaq1RadioButton3.setSelected(false);
            respostaq1RadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_respostaq1RadioButton1ActionPerformed

    private void respostaq1RadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaq1RadioButton2ActionPerformed
        if (respostaq1RadioButton2.isSelected()){
            respostaq1RadioButton1.setSelected(false);
            respostaq1RadioButton3.setSelected(false);
            respostaq1RadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_respostaq1RadioButton2ActionPerformed

    private void respostaq1RadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaq1RadioButton3ActionPerformed
        if (respostaq1RadioButton3.isSelected()){
            respostaq1RadioButton1.setSelected(false);
            respostaq1RadioButton2.setSelected(false);
            respostaq1RadioButton4.setSelected(false);
        }
    }//GEN-LAST:event_respostaq1RadioButton3ActionPerformed

    private void respostaq1RadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaq1RadioButton4ActionPerformed
        if (respostaq1RadioButton4.isSelected()){
            respostaq1RadioButton1.setSelected(false);
            respostaq1RadioButton2.setSelected(false);
            respostaq1RadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_respostaq1RadioButton4ActionPerformed

    private void retornaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornaButtonActionPerformed
        int opcao = JOptionPane.showOptionDialog(
            null,
            "Tem certeza que deseja voltar ao início?",
            "Sair?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Sim", "Não"},
            "Sim"
        );

        if (opcao == JOptionPane.YES_OPTION) {
            dispose(); //Substituir pelo menu inicial
        }
        else{
        }
    }//GEN-LAST:event_retornaButtonActionPerformed

    private void proximoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoButtonActionPerformed
        if (respostaq1RadioButton1.isSelected() || respostaq1RadioButton2.isSelected() || respostaq1RadioButton3.isSelected() || respostaq1RadioButton4.isSelected()){
            var dt = new FrameQuiz2(); //chama uma tela específicao nome para sua tentativa:
            dt.setVisible(true); //faz tal tela ser visível
            dispose(); // descarta a tela atual
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma resposta...");
        }
    }//GEN-LAST:event_proximoButtonActionPerformed

    private void perguntaLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perguntaLabel1AncestorAdded
        String pergunta = "Pergunta 1";
        //Questao q = new Questao(pergunta);
        //var dao = new QuestaoDAO();
        //String pg = dao.existe(Questao q);
        perguntaLabel1.setText(pergunta); //Aqui é onde o enunciado é definido, não deu certo...
    }//GEN-LAST:event_perguntaLabel1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameQuiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameQuiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameQuiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameQuiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameQuiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel perguntaLabel1;
    private javax.swing.JButton proximoButton;
    private javax.swing.JRadioButton respostaq1RadioButton1;
    private javax.swing.JRadioButton respostaq1RadioButton2;
    private javax.swing.JRadioButton respostaq1RadioButton3;
    private javax.swing.JRadioButton respostaq1RadioButton4;
    private javax.swing.JButton retornaButton;
    // End of variables declaration//GEN-END:variables

    private String toString(QuestaoDAO dao) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
